# =============================================================================
# Two-Stage Training Pipeline for TAHIMIK
#
# All three model variants follow the same two-stage training procedure
# (control variable) so that any performance differences are attributable
# solely to the compression mechanism:
#
#   Stage 1 - Synthetic Pretraining:
#     Train on ~1M synthetic noisy-clean pairs generated by the noise
#     pipeline. 3 epochs, batch size 16, 90/10 train/val split.
#     Purpose: teach the model the general structure of Filipino noise.
#
#   Stage 2 - Gold Standard Fine-tuning:
#     Fine-tune on ~15K human-annotated pairs. 10 epochs, batch size 8,
#     80/10/10 train/val/test split.
#     Purpose: calibrate on real social media noise distributions.
#
# Both stages use AdamW with cosine LR scheduling and 6% warmup.
# Mixed precision (fp16) is enabled by default for Colab A100 training.
# =============================================================================

import os
import time
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.cuda.amp import GradScaler, autocast
from transformers import get_scheduler
from typing import Dict, Optional

from src.training.losses import TAHIMIKLoss
from src.data.dataset import NormalizationDataset, collate_fn
from src.utils.logging_utils import setup_logger
from src.utils.reproducibility import collect_run_metadata

logger = setup_logger("tahimik.trainer")


class TAHIMIKTrainer:
    """
    Two-stage trainer for all TAHIMIK model variants.

    Handles the full training loop including:
        - AdamW optimizer with cosine LR scheduling
        - Mixed-precision (fp16) training
        - Gradient clipping
        - Checkpoint saving (best validation loss)
        - Training/validation logging per epoch

    Args:
        model: One of ByT5Baseline, FixedCompressionByT5, or NoiseAdaptiveByT5.
        config: The corresponding config (ByT5Config / MrT5Config / TAHIMIKConfig).
        loss_fn: A TAHIMIKLoss instance configured for this variant.
    """

    def __init__(self, model, config, loss_fn: TAHIMIKLoss):
        self.model = model
        self.config = config
        self.loss_fn = loss_fn

        self.device = torch.device(
            config.device if torch.cuda.is_available() else "cpu"
        )
        self.model.to(self.device)

        self.fp16 = config.fp16 and self.device.type == "cuda"
        self.scaler = GradScaler(enabled=self.fp16)

        # Best validation loss for checkpoint selection
        self.best_val_loss = float("inf")

    def _create_optimizer(self) -> torch.optim.Optimizer:
        """Create AdamW optimizer with the config's hyperparameters."""
        return torch.optim.AdamW(
            self.model.parameters(),
            lr=self.config.learning_rate,
            betas=(self.config.adam_beta1, self.config.adam_beta2),
            eps=self.config.adam_epsilon,
            weight_decay=self.config.weight_decay,
        )

    def _create_scheduler(self, optimizer, num_training_steps):
        """Create cosine LR scheduler with warmup."""
        num_warmup_steps = int(num_training_steps * self.config.warmup_ratio)
        return get_scheduler(
            name=self.config.lr_scheduler_type,
            optimizer=optimizer,
            num_warmup_steps=num_warmup_steps,
            num_training_steps=num_training_steps,
        )

    def _train_epoch(
        self,
        dataloader: DataLoader,
        optimizer: torch.optim.Optimizer,
        scheduler,
    ) -> Dict[str, float]:
        """Run one training epoch."""
        self.model.train()
        total_losses = {}
        num_batches = 0

        for batch in dataloader:
            batch = {k: v.to(self.device) for k, v in batch.items()}

            optimizer.zero_grad()

            with autocast(enabled=self.fp16):
                model_outputs = self.model(
                    input_ids=batch["input_ids"],
                    attention_mask=batch["attention_mask"],
                    labels=batch["labels"],
                    noise_level=batch.get("noise_level"),
                )

                losses = self.loss_fn(
                    model_outputs,
                    noise_level=batch.get("noise_level"),
                )

            # Backward pass with gradient scaling
            self.scaler.scale(losses["total_loss"]).backward()

            # Gradient clipping
            self.scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(
                self.model.parameters(), self.config.max_grad_norm
            )

            self.scaler.step(optimizer)
            self.scaler.update()
            scheduler.step()

            # Accumulate losses for logging
            for key, val in losses.items():
                if key not in total_losses:
                    total_losses[key] = 0.0
                total_losses[key] += val.item()
            num_batches += 1

        # Average over batches
        avg_losses = {k: v / num_batches for k, v in total_losses.items()}
        return avg_losses

    @torch.no_grad()
    def _validate(self, dataloader: DataLoader) -> Dict[str, float]:
        """Run validation and return average losses."""
        self.model.eval()
        total_losses = {}
        num_batches = 0

        for batch in dataloader:
            batch = {k: v.to(self.device) for k, v in batch.items()}

            with autocast(enabled=self.fp16):
                model_outputs = self.model(
                    input_ids=batch["input_ids"],
                    attention_mask=batch["attention_mask"],
                    labels=batch["labels"],
                    noise_level=batch.get("noise_level"),
                )

                losses = self.loss_fn(
                    model_outputs,
                    noise_level=batch.get("noise_level"),
                )

            for key, val in losses.items():
                if key not in total_losses:
                    total_losses[key] = 0.0
                total_losses[key] += val.item()
            num_batches += 1

        avg_losses = {k: v / max(num_batches, 1) for k, v in total_losses.items()}
        return avg_losses

    def _save_checkpoint(self, epoch: int, stage: str, val_loss: float):
        """Save model checkpoint if validation loss improved."""
        if val_loss < self.best_val_loss:
            self.best_val_loss = val_loss
            checkpoint_dir = os.path.join(
                self.config.checkpoint_dir,
                self.config.variant_name,
            )
            os.makedirs(checkpoint_dir, exist_ok=True)

            path = os.path.join(
                checkpoint_dir, f"best_{stage}.pt"
            )
            torch.save({
                "epoch": epoch,
                "stage": stage,
                "model_state_dict": self.model.state_dict(),
                "val_loss": val_loss,
            }, path)
            logger.info(f"  Saved checkpoint: {path} (val_loss={val_loss:.4f})")

    def train_stage(
        self,
        stage_name: str,
        train_dataset: NormalizationDataset,
        val_dataset: NormalizationDataset,
        epochs: int,
        batch_size: int,
    ) -> Dict[str, list]:
        """
        Run one training stage (Stage 1 or Stage 2).

        Args:
            stage_name: "stage1" or "stage2" (for logging and checkpoint naming).
            train_dataset: Training split NormalizationDataset.
            val_dataset: Validation split NormalizationDataset.
            epochs: Number of training epochs for this stage.
            batch_size: Batch size for this stage.

        Returns:
            History dict with per-epoch train and val losses.
        """
        logger.info(f"{'='*60}")
        logger.info(f"Starting {stage_name}: {epochs} epochs, batch_size={batch_size}")
        logger.info(f"  Train samples: {len(train_dataset)}")
        logger.info(f"  Val samples:   {len(val_dataset)}")
        logger.info(f"{'='*60}")

        train_loader = DataLoader(
            train_dataset,
            batch_size=batch_size,
            shuffle=True,
            collate_fn=collate_fn,
            num_workers=0,
            pin_memory=self.device.type == "cuda",
        )
        val_loader = DataLoader(
            val_dataset,
            batch_size=self.config.eval_batch_size,
            shuffle=False,
            collate_fn=collate_fn,
            num_workers=0,
            pin_memory=self.device.type == "cuda",
        )

        optimizer = self._create_optimizer()
        num_training_steps = len(train_loader) * epochs
        scheduler = self._create_scheduler(optimizer, num_training_steps)

        history = {"train": [], "val": []}

        for epoch in range(1, epochs + 1):
            epoch_start = time.time()

            # Train
            train_losses = self._train_epoch(train_loader, optimizer, scheduler)
            # Validate
            val_losses = self._validate(val_loader)

            epoch_time = time.time() - epoch_start

            history["train"].append(train_losses)
            history["val"].append(val_losses)

            # Log
            logger.info(
                f"  [{stage_name}] Epoch {epoch}/{epochs} "
                f"({epoch_time:.1f}s) - "
                f"train_loss={train_losses['total_loss']:.4f} "
                f"val_loss={val_losses['total_loss']:.4f}"
            )

            # Log component losses if present
            for key in ["l_ce", "l_rate", "l_attn_reg", "l_ne"]:
                if key in train_losses:
                    logger.info(
                        f"    {key}: train={train_losses[key]:.4f} "
                        f"val={val_losses[key]:.4f}"
                    )

            # Checkpoint
            self._save_checkpoint(epoch, stage_name, val_losses["total_loss"])

        return history

    def train(
        self,
        stage1_train: Optional[NormalizationDataset] = None,
        stage1_val: Optional[NormalizationDataset] = None,
        stage2_train: Optional[NormalizationDataset] = None,
        stage2_val: Optional[NormalizationDataset] = None,
    ) -> Dict[str, Dict]:
        """
        Run the full two-stage training pipeline.

        Stage 1 is skipped if stage1_train/stage1_val are None (useful
        for debugging with gold data only).

        Args:
            stage1_train, stage1_val: Synthetic pretraining datasets.
            stage2_train, stage2_val: Gold standard fine-tuning datasets.

        Returns:
            Dict with 'stage1' and 'stage2' history dicts.
        """
        full_history = {}

        # --- Stage 1: Synthetic Pretraining ----------------------------------
        if stage1_train is not None and stage1_val is not None:
            self.best_val_loss = float("inf")
            stage1_history = self.train_stage(
                stage_name="stage1",
                train_dataset=stage1_train,
                val_dataset=stage1_val,
                epochs=self.config.stage1_epochs,
                batch_size=self.config.stage1_batch_size,
            )
            full_history["stage1"] = stage1_history
        else:
            logger.info("Skipping Stage 1 (no synthetic data provided)")

        # --- Stage 2: Gold Standard Fine-tuning ------------------------------
        if stage2_train is not None and stage2_val is not None:
            self.best_val_loss = float("inf")
            stage2_history = self.train_stage(
                stage_name="stage2",
                train_dataset=stage2_train,
                val_dataset=stage2_val,
                epochs=self.config.stage2_epochs,
                batch_size=self.config.stage2_batch_size,
            )
            full_history["stage2"] = stage2_history
        else:
            logger.info("Skipping Stage 2 (no gold standard data provided)")

        logger.info("Training complete.")
        return full_history

    def load_checkpoint(self, checkpoint_path: str):
        """Load a saved checkpoint into the model."""
        checkpoint = torch.load(
            checkpoint_path, map_location=self.device, weights_only=True
        )
        self.model.load_state_dict(checkpoint["model_state_dict"])
        logger.info(
            f"Loaded checkpoint from {checkpoint_path} "
            f"(epoch={checkpoint['epoch']}, "
            f"stage={checkpoint['stage']}, "
            f"val_loss={checkpoint['val_loss']:.4f})"
        )

