# Standard ByT5 baseline wrapper for text normalization without byte compression.

import torch
import torch.nn as nn
from transformers import AutoTokenizer, T5ForConditionalGeneration
from typing import Dict, Optional


class ByT5Baseline(nn.Module):
    """
    Standard uncompressed ByT5 model wrapper.

    Args:
        config: A ByT5Config (or BaseConfig) instance.
    """

    def __init__(self, config):
        super().__init__()

        self.config = config
        self.model = T5ForConditionalGeneration.from_pretrained(
            config.model_name
        )
        self.tokenizer = AutoTokenizer.from_pretrained(config.model_name)

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        labels: Optional[torch.Tensor] = None,
        **kwargs,
    ) -> Dict[str, torch.Tensor]:
        """
        Standard ByT5 forward pass.

        Args:
            input_ids: Byte-level input IDs. Shape: (batch, seq_len)
            attention_mask: Binary mask. Shape: (batch, seq_len)
            labels: Target byte IDs with -100 for padding. Shape: (batch, target_len)

        Returns:
            Dict with 'loss' (if labels provided), 'logits', and metadata.
        """
        outputs = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels,
        )

        result = {
            "logits": outputs.logits,
            "encoder_last_hidden_state": outputs.encoder_last_hidden_state,
            # No compression — deletion rate is always 0
            "deletion_rate": torch.zeros(
                input_ids.size(0), device=input_ids.device
            ),
        }

        if labels is not None:
            result["loss"] = outputs.loss

        return result

    def generate(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        max_length: int = 1024,
        num_beams: int = 4,
        **kwargs,
    ) -> torch.Tensor:
        """
        Generate normalized text via beam search.

        Args:
            input_ids: Byte-level input IDs.
            attention_mask: Binary mask.
            max_length: Maximum output length in bytes.
            num_beams: Beam search width.

        Returns:
            Generated byte IDs. Shape: (batch, output_len)
        """
        return self.model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=max_length,
            num_beams=num_beams,
            early_stopping=True,
        )

    def generate_with_telemetry(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        max_length: int = 1024,
        num_beams: int = 4,
    ) -> tuple[torch.Tensor, list[dict]]:
        """Generate and report that the uncompressed baseline deletes nothing."""
        generated = self.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=max_length,
            num_beams=num_beams,
        )
        input_counts = attention_mask.sum(dim=1).detach().cpu().tolist()
        telemetry = [
            {
                "compression_mode": "none",
                "input_token_count": int(count),
                "kept_token_count": int(count),
                "deleted_token_count": 0,
                "deletion_rate": 0.0,
            }
            for count in input_counts
        ]
        return generated, telemetry
