# =============================================================================
# ByT5 Baseline — No Compression (Accuracy Ceiling)
#
# This is the first of three model variants compared in the study.
# It wraps the standard ByT5 encoder-decoder without any delete gate
# or compression, establishing the maximum achievable normalization
# accuracy when every byte is processed by every encoder layer.
#
# All three variants share the same tokenizer, optimizer, data splits,
# and training schedule (control variables) — only the compression
# mechanism differs (independent variable).
# =============================================================================
import torch
import torch.nn as nn
from transformers import AutoTokenizer, T5ForConditionalGeneration
from typing import Dict, Optional


class ByT5Baseline(nn.Module):
    """
    Vanilla ByT5 for text normalization (no compression).

    This model serves as the accuracy ceiling: since no bytes are deleted,
    the encoder has full access to the input. Any accuracy loss in MrT5
    or TAHIMIK relative to this baseline is attributable to compression.

    Args:
        config: A ByT5Config (or BaseConfig) instance.
    """

    def __init__(self, config):
        super().__init__()

        self.config = config
        self.model = T5ForConditionalGeneration.from_pretrained(
            config.model_name
        )
        self.tokenizer = AutoTokenizer.from_pretrained(config.model_name)

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        labels: Optional[torch.Tensor] = None,
        **kwargs,
    ) -> Dict[str, torch.Tensor]:
        """
        Standard ByT5 forward pass.

        Args:
            input_ids: Byte-level input IDs. Shape: (batch, seq_len)
            attention_mask: Binary mask. Shape: (batch, seq_len)
            labels: Target byte IDs with -100 for padding. Shape: (batch, target_len)

        Returns:
            Dict with 'loss' (if labels provided), 'logits', and metadata.
        """
        outputs = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels,
        )

        result = {
            "logits": outputs.logits,
            "encoder_last_hidden_state": outputs.encoder_last_hidden_state,
            # No compression — deletion rate is always 0
            "deletion_rate": torch.zeros(
                input_ids.size(0), device=input_ids.device
            ),
        }

        if labels is not None:
            result["loss"] = outputs.loss

        return result

    def generate(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor,
        max_length: int = 1024,
        num_beams: int = 4,
        **kwargs,
    ) -> torch.Tensor:
        """
        Generate normalized text via beam search.

        Args:
            input_ids: Byte-level input IDs.
            attention_mask: Binary mask.
            max_length: Maximum output length in bytes.
            num_beams: Beam search width.

        Returns:
            Generated byte IDs. Shape: (batch, output_len)
        """
        return self.model.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=max_length,
            num_beams=num_beams,
            early_stopping=True,
        )
